-- Table: public.brush_records

CREATE TABLE public.brush_records (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp  TIMESTAMPTZ NOT NULL,
  duration   BIGINT NOT NULL,
  device     TEXT NOT NULL
);
